name: 'card-move'
on:
  project_card:
    types:
      - created

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - id: step1
        uses: actions/github-script@v3
        with:
          script: |
            let result;
            switch (context.project_card.column_id) {
              case: 12497383
                result = 'test'
              default:
                result = 'unknown'
            }
          result-encoding: string
      - id: step2
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          custom_payload: |
            {
              username: 'Kudos Bot',
              icon_emoji: ':octocat:',
              text: "${{ github.event.project_card.creator.login }}より${{ steps.step1.outputs.result }}へ感謝のお気持ちが届いています",
              attachments: [{
                fallback: 'fallback',
                color: 'good',
                text: "${{ github.event.project_card.note }}"
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}