name: 'card-move'
on:
  project_card:
    types:
      - created

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - id: step1
        run: |
          echo "user: ${{ github.event.project_card.creator.login }}"
          echo "note: ${{ github.event.project_card.note }}"
          echo "column_url: ${{ github.event.project_card.column_url }}"