name: 'card-move'
on:
  project_card:
    types:
      - created

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      to_username: ${{ steps.set-matrix.outputs.to_username }}
    steps:
    - id: set-to-username
      if: ${{ github.event.project_card.column_id }} == 12497383
      run: echo "::set-output name=to_username::test"
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - id: step1
        run: |
          echo "user: ${{ github.event.project_card.creator.login }}"
          echo "note: ${{ github.event.project_card.note }}"
          echo "column_url: ${{ github.event.project_card.column_url }}"
      - id: step2
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          custom_payload: |
            {
              username: 'Kudos Bot',
              icon_emoji: ':octocat:',
              text: "${{ github.event.project_card.creator.login }}より${{ needs.job1.outputs.to_username }}へ感謝のお気持ちが届いています",
              attachments: [{
                fallback: 'fallback',
                color: 'good',
                text: "${{ github.event.project_card.note }}"
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}