name: 'build-test'
on:
  issue_comment:
    types:
      - created
      - edited

jobs:
  check:
    if: contains(github.event.pull_request.labels.*.name, 'finance') && github.event.comment.body == '@github 承認'
    runs-on: ubuntu-latest

    steps:
      - name: Comment Checking
        run: |
          echo "Comment Checking" |
          echo "body: ${{ github.event.comment.body }}"
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all