name: 'pr'
on:
  pull_request:
    types:
      - opened
      - edited

jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
      - id: step1
        uses: fukuiretu/actions-pr-changed-files-matcher@main
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          s3-bucket: "2021-fukuiretu-data"
          s3-key: "test/list-20210223.txt"
